### ISSUE TITLE
Thread hangs reading socket

### ISSUE THREAD

**Issue by aunfl0w** [aunfl0w/frozen-particle-waves#4]
`
"Thread-2" #59 daemon prio=5 os_prio=0 tid=0x00007fc8c82a8000 nid=0xade runnable [0x00007fc8a13ba000]
   java.lang.Thread.State: RUNNABLE
        at java.net.SocketInputStream.socketRead0(java.base@9-internal/Native Method)
        at java.net.SocketInputStream.socketRead(java.base@9-internal/SocketInputStream.java:116)
        at java.net.SocketInputStream.read(java.base@9-internal/SocketInputStream.java:170)
        at java.net.SocketInputStream.read(java.base@9-internal/SocketInputStream.java:141)
        at java.io.BufferedInputStream.fill(java.base@9-internal/BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read1(java.base@9-internal/BufferedInputStream.java:286)
        at java.io.BufferedInputStream.read(java.base@9-internal/BufferedInputStream.java:345)
        - locked <0x00000000f59b9910> (a java.io.BufferedInputStream)
        at java.io.FilterInputStream.read(java.base@9-internal/FilterInputStream.java:133)
        at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(java.base@9-internal/HttpURLConnection.java:3347)
        at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(java.base@9-internal/HttpURLConnection.java:3340)
        at fpw.domain.image.camera.BasicURLCamera.getImage(BasicURLCamera.java:40)
        at fpw.service.QueueImageService.run(QueueImageService.java:27)
        at java.lang.Thread.run(java.base@9-internal/Thread.java:804)
`

**Comment by aunfl0w** [comment]
possible fix in 
7cf905ab5df852a7774623cd43850b381eb7e948

**Comment by aunfl0w** [comment]
looks like this bug : https://bugs.openjdk.java.net/browse/JDK-8172578

**Comment by aunfl0w** [comment]
This issue has been resolved with JDK 11+
